// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';

export function GetRecentLogs(arg1:number):Promise<Array<storage.SpendRecord>>;

export function GetStatus():Promise<main.SystemStatus>;

export function SaveAPIKey(arg1:string):Promise<string>;
