// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}
